name: Auto Post (Every 30 minutes)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate image + caption
        env:
          OUTPUT_DIR: out
          BRAND_NAME: instanews
          NEWS_WINDOW_HOURS: "6"
          FORCE_GENERATE: "1"
        run: python auto_news_instagram.py

      - name: Show output dir and print Final URL
        run: |
          ls -la out || true
          if [ -f out/url.txt ]; then
            echo "====================================="
            echo "FINAL IMAGE URL:"
            cat out/url.txt
            echo "====================================="
          else
            echo "No URL file found."
          fi

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4