name: Generate Market Poster (Image Only)

on:
  schedule:
    - cron: "0 * * * *"   # हर 1 घंटे; चाहें तो बदलें
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          python generate_post.py
          if [ -n "$(git status --porcelain out/)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add out/
            git commit -m "chore: add generated image"
            git push
          else
            echo "No new image to commit."
          fi