name: Generate Market Poster (Latest Only)

on:
  schedule:
    - cron: "*/30 * * * *"  # हर 30 मिनट (UTC). चाहें तो 15/20 भी कर सकते हैं
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      MAX_AGE_MINUTES: "60"     # 👈 खबर इससे पुरानी हुई तो इमेज नहीं बनेगी
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate (fresh-only)
        run: |
          python generate_latest_post.py
      - name: Commit fresh image (if any)
        run: |
          if [ -n "$(git status --porcelain out/)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add out/
            git commit -m "chore: add fresh image"
            git push
          else
            echo "Nothing to commit (no fresh news or duplicate)."
          fi